version: '3'

services:
  mysql-db:
    container_name: mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=olounge