spring:
  jpa:
    database: MYSQL
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  datasource:
    url: jdbc:mysql://localhost:3306/optionslounge?useSSL=false
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/tradeRepo

server:
  port: 8081