spring:
  jpa:
    database: H2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

#
#    data:
#      mongodb:
#        host: 127.0.0.1
#        port: 0
#        database: embeddedDB